Repository Webpage-builder/HackerRank, pull requests merged in 2020-10, with the labels that each got.

#4 Some CPP solutions for hackerrank problems
  CPP/Accesing Inherited Functions.cpp
  CPP/Rectangle Area.cpp
  CPP/Sets-STL.cpp
  CPP/Vector Sort.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#5 Rename abstract_class.py to python/abstract_class.py
  python/abstract_class.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#7 added some more c++ solutions
  CPP/Attribute Parser.cpp
  CPP/Exceptional Server.cpp
  CPP/Inherited code.cpp
  CPP/Virtual functions.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#8 Create stock_maximize.py
  Python/stock_maximize.py
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added new hackerank solutions for C
  C/AVeryBigSum.c
  C/CompareTheTriplets.c
  C/SimpleArraySum.c
  C/SolveMeFirst.c
Labels: hacktoberfest, hacktoberfest-accepted

#11 Add files via upload
  CPP/Multiplication Matrix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#12 added some more solutions
  CPP/Hotel Prices.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#9 Create bin_search.py
  Python/binary_search.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 Euler's totient function
  CPP/Euler_totient_function.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#15 Rabin-Karp Algorithm for string matching
  CPP/Rabin-Karp.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#16 Added more C solutions
  C/AppleAndOrange.c
  C/BirthdayCakeCandles.c
  C/DiagonalDifference.c
  C/GradingStudents.c
  C/Kangaroo.c
  C/MiniMaxSum.c
  C/PlusMinus.c
  C/Staircase.c
  C/TImeConversion.c
Labels: hacktoberfest, hacktoberfest-accepted

#17 Tic Tac Toe Game in CPlusPlus
  CPP/TIC TAC TOE.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#18 Suffix Tree - Ukkonen's Algorithm
  CPP/Suffix_tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#19 Dijkstra Algorithm
  CPP/Dijkstra Algorithm
Labels: hacktoberfest, hacktoberfest-accepted

#21 Python Fun Program
  Python/Lottery_simulation.py
Labels: hacktoberfest, hacktoberfest-accepted

#22 Update binary_search.py
  Python/binary_search.py
Labels: hacktoberfest, hacktoberfest-accepted
